# Master Detail Layout Component (Experimental)
com.vaadin.experimental.masterDetailLayoutComponent=true

# Slider Component (Experimental)
com.vaadin.experimental.sliderComponent=true

# Badge Component (Experimental)
com.vaadin.experimental.badgeComponent=true
