package com.vaadin.jandex;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.CompositeIndex;
import org.jboss.jandex.DotName;
import org.jboss.jandex.Index;
import org.jboss.jandex.IndexReader;
import org.jboss.jandex.IndexView;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import com.vaadin.flow.component.charts.model.ChartConfiguration;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.server.HandlerHelper;

public class JandexSmokeTest {

    private static final String JANDEX_INDEX = "META-INF/jandex.idx";

    /** The index generated by this module, from target/classes. */
    private static Index aggregateIndex;

    /** Indexes shipped by the dependency jars themselves. */
    private static final List<Index> artifactIndexes = new ArrayList<>();
    private static final List<URL> artifactIndexUrls = new ArrayList<>();

    @BeforeClass
    public static void readIndexes() throws IOException {
        for (URL url : Collections.list(JandexSmokeTest.class.getClassLoader()
                .getResources(JANDEX_INDEX))) {
            Index index = read(url);
            if ("file".equals(url.getProtocol())) {
                Assert.assertNull("Found more than one aggregate index",
                        aggregateIndex);
                aggregateIndex = index;
            } else {
                artifactIndexes.add(index);
                artifactIndexUrls.add(url);
            }
        }
        Assert.assertNotNull("Aggregate index was not generated",
                aggregateIndex);
    }

    @Test
    public void generatedJandex_doesNotContainClassesFromIndexedArtifacts() {
        for (int i = 0; i < artifactIndexes.size(); i++) {
            Index artifactIndex = artifactIndexes.get(i);
            String duplicates = artifactIndex.getKnownClasses().stream()
                    .map(ClassInfo::name)
                    .filter(name -> aggregateIndex.getClassByName(name) != null)
                    .map(DotName::toString).sorted()
                    .collect(Collectors.joining(", "));
            Assert.assertTrue("Classes already indexed in "
                    + artifactIndexUrls.get(i)
                    + " were added to the aggregate index: " + duplicates,
                    duplicates.isEmpty());
        }
    }

    @Test
    public void generatedJandex_containsContentFromFlowAndComponents() {
        IndexView allIndexes = CompositeIndex.create(
                concat(aggregateIndex, artifactIndexes));

        Assert.assertNotNull("Class from flow-server was not found",
                allIndexes.getClassByName(HandlerHelper.class));
        Assert.assertNotNull("Class from a component was not found",
                allIndexes.getClassByName(VerticalLayout.class));
        Assert.assertNotNull("Class from commercial component was missing",
                allIndexes.getClassByName(ChartConfiguration.class));
    }

    @Test
    public void generatedJandex_shouldNotContainsOptionalDependencies() {
        Assert.assertNull("Class from vaadin-dev-server was found",
                aggregateIndex.getClassByName(
                        "com.vaadin.base.devserver.startup.DevModeStartupListener"));
        Assert.assertNull("Class from flow-react was found",
                aggregateIndex.getClassByName(
                        "com.vaadin.flow.component.react.ReactAdapterComponent"));
        Assert.assertNull("Class from copilot was found",
                aggregateIndex.getClassByName("com.vaadin.copilot.Copilot"));
    }

    private static Index read(URL url) throws IOException {
        try (InputStream jandexStream = url.openStream()) {
            return new IndexReader(jandexStream).read();
        }
    }

    private static List<IndexView> concat(Index first, List<Index> rest) {
        List<IndexView> all = new ArrayList<>(rest);
        all.add(first);
        return all;
    }
}
