blank_issues_enabled: false
contact_links:
  - name: Vaadin discord chat
    url: https://discord.gg/vaadin
    about: You can ask question for fast responds here.
  - name: Report a security vulnerability
    url: https://github.com/vaadin/platform/security/policy
    about: Please review our security policy for more details
