name: PRD
description: Product Requirements Document
labels: ["PRD"]
body:

- type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Brief description of the feature (max ~30 words)
    validations:
      required: true

- type: dropdown
    id: tier
    attributes:
      label: Tier
      options:
        - Free
        - Plus
        - Pro
        - Premium
        - Ultimate
      value: Free
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: License
      options:
        - Apache 2.0
        - Proprietary
      value: Apache 2.0
    validations:
      required: true

- type: textarea
  id: motivation
  attributes:
    label: Motivation
    value: |
      "#### Background" |
      | (optional)
      |
      "#### Problem" |
      |
      "#### Solution" |
      |
      "#### Notes" |
      | (optional)
      |
      | (Remove unused sections)
  validations:
    required: true

- type: textarea
  id: requirements
  attributes:
    label: Requirements
    description: Once the PRD is approved, sub-issues are created in the appropriate repository. These items are checked once there are issues covering them and progress is tracked through the sub-issues.
    value: |
      - [ ] Requirement 1
      - [ ] Requirement 2
      - [ ] Requirement 3
  validations:
    required: true

- type: checkboxes
  id: standard-requirement-options
  attributes:
    label: Standard requirements
    description: Check those that apply.
    options:
      - License check
      - Feature flag
      - Copilot support
      - Figma-library support
      - Accessibility requirements apply

- type: textarea
  id: nice-to-haves
  attributes:
    label: Nice-to-haves
    description: (Optional)
    value: |
      - [ ] Nice-to-have 1
      - [ ] Nice-to-have 2
      - [ ] Nice-to-have 3
  validations:
    required: false

- type: textarea
  id: limitations-risks
  attributes:
    label: Risks, limitations and breaking changes
    value: |
      "#### Risks" |
      | Known risks that should be mitigated during implementation.
      |
      "#### Limitations" |
      | Expected limitations that can be accepted if no workaround is found.
      |
      "#### Breaking changes" |
      |
      | (Remove unused sections)
  validations:
    required: false

- type: textarea
  id: out-of-scope
  attributes:
    label: Out of scope
    description: Things that are explicitly out of scope that we feel are worth noting, including plans for future development.
  validations:
    required: false

- type: textarea
  id: materials
  attributes:
    label: Materials
    description: RFC, designs, prototypes, discussion threads, etc.
  validations:
    required: false

- type: markdown
  attributes:
    value: "## Filled before implementation"

- type: input
  id: estimate
  attributes:
    label: Estimate
    description: man-days
  validations:
    required: false  

- type: checkboxes
  id: pre-impl-checklist
  attributes:
    label: Pre-implementation checklist
    options:
      - Estimated
      - Engineering Manager sign-off
      - Product Manager sign-off
  validations:
    required: false  

- type: markdown
  attributes:
    value: "## Filled before release"

- type: textarea
  id: docs
  attributes:
    label: Link(s) to documentation
  validations:
    required: false  

- type: checkboxes
  id: pre-release-checklist
  attributes:
    label: Pre-release checklist
    options:
      - Documented
      - Security review conducted and risks addressed
      - UX/DX tests conducted and blockers addressed
      - Product Manager sign-off
  validations:
    required: false

- type: textarea
  id: metrics
  attributes:
    label: Metrics
    description: Tracked metrics and success criteria
  validations:
    required: false  
