package com.vaadin.prodbundle;

import com.vaadin.flow.component.accordion.Accordion;
import com.vaadin.flow.component.applayout.AppLayout;
import com.vaadin.flow.component.applayout.DrawerToggle;
import com.vaadin.flow.component.avatar.Avatar;
import com.vaadin.flow.component.avatar.AvatarGroup;
import com.vaadin.flow.component.board.Board;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.combobox.MultiSelectComboBox;
import com.vaadin.flow.component.confirmdialog.ConfirmDialog;
import com.vaadin.flow.component.contextmenu.ContextMenu;
import com.vaadin.flow.component.cookieconsent.CookieConsent;
import com.vaadin.flow.component.crud.Crud;
import com.vaadin.flow.component.customfield.CustomField;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.datetimepicker.DateTimePicker;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.details.Details;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.fieldhighlighter.FieldHighlighterInitializer;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.gridpro.GridPro;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.listbox.ListBox;
import com.vaadin.flow.component.login.LoginForm;
import com.vaadin.flow.component.login.LoginOverlay;
import com.vaadin.flow.component.menubar.MenuBar;
import com.vaadin.flow.component.messages.MessageInput;
import com.vaadin.flow.component.messages.MessageList;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.Scroller;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.progressbar.ProgressBar;
import com.vaadin.flow.component.radiobutton.RadioButtonGroup;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.shared.Tooltip;
import com.vaadin.flow.component.shared.TooltipConfiguration;
import com.vaadin.flow.component.splitlayout.SplitLayout;
import com.vaadin.flow.component.tabs.Tab;
import com.vaadin.flow.component.tabs.TabSheet;
import com.vaadin.flow.component.tabs.Tabs;
import com.vaadin.flow.component.textfield.BigDecimalField;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.IntegerField;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.PasswordField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.timepicker.TimePicker;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.component.upload.Upload;
import com.vaadin.flow.component.virtuallist.VirtualList;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility;

@Route
@JsModule("@vaadin/tooltip/vaadin-tooltip.js")
public class EagerView extends Div {

    public Accordion accordion;
    public AppLayout appLayout;
    public Avatar avatar;
    public AvatarGroup avatarGroup;
    public Board board;
    public BigDecimalField bigDecimalField;
    public Button button;
    public Checkbox checkbox;
    public ComboBox<String> comboBox;
    public ConfirmDialog confirmDialog;
    public ContextMenu contextMenu;
    public CookieConsent cookieConsent;
    public Crud<String> crud;
    public CustomField<String> customField;
    public DatePicker datePicker;
    public DateTimePicker dateTimePicker;
    public Details details;
    public Dialog dialog;
    public DrawerToggle drawerToggle;
    public EmailField emailField;
    public FieldHighlighterInitializer fieldHighlighterInitializer;
    public FormLayout formLayout;
    public Grid<String> grid;
    public GridPro<String> gridPro;
    public HorizontalLayout horizontalLayout;
    public IntegerField integerField;
    public Icon icon;
    public ListBox<String> listBox;
    public LoginOverlay loginOverlay;
    public LoginForm LoginForm;
    public LumoUtility lumoUtility;
    public MenuBar menuBar;
    public MessageInput messageInput;
    public MessageList messageList;
    public MultiSelectComboBox<String> multiSelectComboBox;
    public Notification notification;
    public NumberField numberField;
    public PasswordField passwordField;
    public ProgressBar progressBar;
    public RadioButtonGroup<String> radioButtonGroup;
    public Scroller scroller;
    public Select<String> select;
    public SplitLayout splitLayout;
    public Tabs tabs;
    public Tab tab;
    public TabSheet tabSheet;
    public TextArea textArea;
    public TextField textField;
    public TimePicker timePicker;
    public TreeGrid<String> treeGrid;
    // public Tooltip tooltip;
    // public TooltipConfiguration tooltipConfiguration;
    public Upload upload;
    public VerticalLayout verticalLayout;
    public VirtualList<String> virtualList;

}
