import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

export interface Update {
    section: string;
    name: string;
    field: "javaVersion" | "jsVersion";
    from: string;
    to: string;
}

interface RunOptions {
    cwd?: string;
    allowFailure?: boolean;
}

// All git/gh commands run from the repo root regardless of where the script
// was invoked from. Required because the GitHub Actions workflow sets
// `working-directory: scripts/check-versions`, so without this override
// `git add versions.json` would look in the wrong directory.
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

function run(cmd: string, args: string[], opts: RunOptions = {}): { code: number; stdout: string; stderr: string } {
    const res = spawnSync(cmd, args, {
        cwd: opts.cwd ?? REPO_ROOT,
        encoding: "utf8",
        shell: false,
    });
    if (res.error) throw res.error;
    const code = res.status ?? 1;
    if (code !== 0 && !opts.allowFailure) {
        const detail = [res.stdout, res.stderr].filter(Boolean).join("\n").trim();
        throw new Error(`\`${cmd} ${args.join(" ")}\` failed (exit ${code})${detail ? `:\n${detail}` : ""}`);
    }
    return { code, stdout: res.stdout ?? "", stderr: res.stderr ?? "" };
}

const git = (args: string[], opts?: RunOptions) => run("git", args, opts);
const gh = (args: string[], opts?: RunOptions) => run("gh", args, opts);

export function assertCleanWorkingTree(): void {
    const { stdout } = git(["status", "--porcelain"]);
    if (stdout.trim() !== "") {
        throw new Error(
            "Working tree is not clean. Commit, stash, or discard local changes before using --create-pr:\n" +
                stdout.trimEnd(),
        );
    }
}

export function assertGhAvailable(): void {
    const probe = run("gh", ["auth", "status"], { allowFailure: true });
    if (probe.code !== 0) {
        throw new Error(
            "`gh` CLI is not installed or not authenticated. Install from https://cli.github.com/ and run `gh auth login`.",
        );
    }
}

export function currentBranch(): string {
    return git(["branch", "--show-current"]).stdout.trim();
}

export function findUniqueBranchName(base: string): string {
    const exists = (name: string): boolean => {
        const local = git(["rev-parse", "--verify", "--quiet", `refs/heads/${name}`], { allowFailure: true });
        if (local.code === 0) return true;
        const remote = git(["ls-remote", "--exit-code", "--heads", "origin", name], { allowFailure: true });
        return remote.code === 0;
    };
    if (!exists(base)) return base;
    for (let i = 2; i < 100; i++) {
        const candidate = `${base}-${i}`;
        if (!exists(candidate)) return candidate;
    }
    throw new Error(`Could not find a free branch name under ${base}-{2..99}`);
}

/** Stable prefix used both in commit/PR titles and to find existing PRs to update. */
export const PR_TITLE_PREFIX = "chore: maintenance version bumps";

export function commitTitle(date: string, base: string): string {
    const suffix = base === "main" ? "" : ` [${base}]`;
    return `${PR_TITLE_PREFIX} (${date})${suffix}`;
}

export function commitBody(updates: Update[], base: string): string {
    const lines: string[] = [
        `Automated maintenance-version updates against \`${base}\`, discovered by \`scripts/check-versions\`.`,
        "",
        "## Updates",
        "",
    ];
    for (const u of updates) {
        lines.push(`- \`${u.section}/${u.name}\`: ${u.field} \`${u.from}\` → \`${u.to}\``);
    }
    lines.push("", "_Generated by `scripts/check-versions/src/index.ts`._");
    return lines.join("\n");
}

export function fetchOrigin(refs: string[]): void {
    git(["fetch", "origin", ...refs]);
}

/** Read a file's contents at a given git ref (e.g. `origin/main`). */
export function readFileFromRef(ref: string, path: string): string {
    return git(["show", `${ref}:${path}`]).stdout;
}

export interface ExistingPr {
    number: number;
    headRefName: string;
    title: string;
    url: string;
}

/** Find an open PR targeting `base` whose title starts with PR_TITLE_PREFIX. */
export function findExistingPr(base: string): ExistingPr | null {
    const { stdout } = gh([
        "pr",
        "list",
        "--base",
        base,
        "--state",
        "open",
        "--json",
        "number,headRefName,title,url",
        "--limit",
        "100",
    ]);
    const list = JSON.parse(stdout) as ExistingPr[];
    return list.find((p) => p.title.startsWith(PR_TITLE_PREFIX)) ?? null;
}

/** Create a fresh branch off `origin/<base>` and check it out. */
export function checkoutNewBranchFromBase(branch: string, base: string): void {
    git(["checkout", "-b", branch, `origin/${base}`]);
}

/**
 * Reset an existing remote branch to `origin/<base>` and check it out locally.
 * Used when updating an open PR — the new commit replaces the old one so the
 * PR always reflects a single, current delta against the base.
 */
export function resetBranchToBase(branch: string, base: string): void {
    // Fetch the remote branch in case we don't have it locally yet.
    git(["fetch", "origin", `${branch}:refs/remotes/origin/${branch}`], { allowFailure: true });
    // Delete any stale local copy so we can re-create it at origin/<base>.
    git(["branch", "-D", branch], { allowFailure: true });
    git(["checkout", "-b", branch, `origin/${base}`]);
}

export function commitFiles(files: string[], title: string, body: string): void {
    git(["add", ...files]);
    git(["commit", "-m", title, "-m", body]);
}

export function pushBranch(branch: string): void {
    git(["push", "-u", "origin", branch]);
}

/**
 * Force-push a branch, refusing if the remote has diverged from our knowledge
 * of it. Used for the existing-PR update path.
 */
export function forcePushBranch(branch: string): void {
    git(["push", "--force-with-lease", "-u", "origin", branch]);
}

export function openPullRequest(title: string, body: string, base: string): string {
    const res = gh(["pr", "create", "--base", base, "--title", title, "--body", body]);
    return res.stdout.trim();
}

export function updatePullRequest(prNumber: number, title: string, body: string): void {
    gh(["pr", "edit", String(prNumber), "--title", title, "--body", body]);
}
