name: PiT CC
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        run: |
          GHTK=${GITHUB_TOKEN:-${{secrets.GHTK}}}
          git clone https://${GHTK}@github.com/vaadin/control-center.git
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Set Vaadin license
        run: |
          TB_LICENSE=${{ secrets.TB_LICENSE }}
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TB_LICENSE | cut -d / -f1`'","proKey":"'`echo $TB_LICENSE | cut -d / -f2`'"}' > ~/.vaadin/proKey
      - name: Build images
        working-directory: control-center
        run: |
          mvn -ntp -B -pl :control-center-app -Pproduction -DskipTests -am install
          mvn -ntp -B -pl :control-center-app -Pproduction -Ddocker.tag=ci docker:build
          mvn -ntp -B -pl :control-center-keycloak package -Ddocker.tag=ci docker:build
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Set up cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
      - name: Load images
        run: |
          kind load docker-image vaadin/control-center-app:ci
          kind load docker-image vaadin/control-center-keycloak:ci
      - name: Install chart
        working-directory: control-center
        run: |
          ct install --config ct.yaml --charts charts/control-center